version: '3.8'

services:
  vpaas:
    image: ghcr.io/coollabsio/coolify:${TAG:-latest}
    restart: always
    container_name: vpaas
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - 'vpaas-local-backup:/app/backups'
      - 'vpaas-db:/app/db'
      - 'vpaas-logs:/app/logs'
      - 'vpaas-ssl-certs:/app/ssl'
      - 'vpaas-traefik-letsencrypt:/etc/traefik/acme'
      - 'vpaas-letsencrypt:/etc/letsencrypt'
      - '/var/run/docker.sock:/var/run/docker.sock'
    env_file:
      - '.env'
    networks:
      - vpaas-infra
  fluent-bit:
    image: ghcr.io/coollabsio/fluent-bit:1.0.0
    container_name: vpaas-fluentbit
    volumes:
      - 'vpaas-logs:/app/logs'
    networks:
      - vpaas-infra
networks:
  vpaas-infra:
    attachable: true
    name: vpaas-infra

volumes:
  vpaas-local-backup:
    name: vpaas-local-backup
  vpaas-logs:
    name: vpaas-logs
  vpaas-db:
    name: vpaas-db
  vpaas-pgdb:
    name: vpaas-pgdb
  vpaas-ssl-certs:
    name: vpaas-ssl-certs
  vpaas-letsencrypt:
    name: vpaas-letsencrypt
  vpaas-traefik-letsencrypt:
    name: vpaas-traefik-letsencrypt
